"""agent permissions and meeting settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 03:07:00.480618
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('permissions', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('meetings', sa.Column('style', sa.String(), server_default='discussion', nullable=False))
    op.add_column('meetings', sa.Column('options', sa.JSON(), server_default='{}', nullable=False))
    op.add_column('meetings', sa.Column('task_ids', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'task_ids')
    op.drop_column('meetings', 'options')
    op.drop_column('meetings', 'style')
    op.drop_column('agents', 'permissions')
    # ### end Alembic commands ###
